title: Pin Li # your name (or website title) here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Business Analytics Candidate 
  <br>
  (STEM Certified)
   <br>
  Proficient in Python, R, SQL 
  <br>
  Simon Business School
  <br>
  University of Rochester
  <br>
  <a href="https://www.linkedin.com/in/lpin/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
